import "../styles/globals.css";
import type { AppProps } from "next/app";
import { ChakraProvider } from "@chakra-ui/react";
import { theme } from "../theme/index";
import { Header } from "../components/organisms/Header";
import { supabase } from "../utils/supabase";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useLoadings } from "../Hooks/useLoadings";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>spla3 team generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Component {...pageProps} />
    </ChakraProvider>
  );
}
