import { Html, Head, Main, NextScript } from "next/document";
import { Header } from "../components/organisms/Header";

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>spla3 team generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
